#!/Users/atharva/Documents/GitHub/Python_Pratice_DataScience/py_venv/bin/python3.12
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))
